# Project information
site_name: "Pteredactyl Documentation"
site_description: "Documentation Site for the Pteredactyl Python Module, Gradio Webapp, API."
site_author: "Matt Stammers, Cai Davis, Michael George"
site_url: "https://github.com/MattStammers/Pteredactyl"

# Copyright
copyright: "2024 SETT Data and AI"

# Repository
repo_name: "Pteredactyl GitHub"
repo_url: "https://github.com/MattStammers/Pteredactyl"
edit_uri: "https://github.com/MattStammers/Pteredactyl/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "red"
    accent: "purple"
  features:
    - tabs

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"


plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]
          selection:
            filters:
              - "!^_[^_]"
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"
  - "assets/js/custom.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"

extra_css:
  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/atom-one-dark.min.css"
  - "assets/css/custom.css"

extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/MattStammers"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/MattStammers_"

# Page tree
nav:
  - Home: index.md
  - Abstract: abstract.md
  - Python_Module:
    - Introduction: Python_Module/landing.md
    - Quickstart: Python_Module/quickstart.md
    - Examining Results: Python_Module/examining_results.md
    - Reusing An Analyser: Python_Module/reusing_an_analyser.md
    - Selecting Entities To Redact: Python_Module/selecting_entities_to_redact.md
    - Passing Custom Regex Entities: Python_Module/passing_custom_regex_entities.md
    - Anonymising DataFrames: Python_Module/anonymising_dataframes.md
    - Mkdocstrings: Python_Module/mkdocstrings.md
    - Developing/Contributing: Python_Module/developing-contributing.md
  - Webapp-API:
      - Introduction: Webapp-API/introduction.md
      - Gradio: Webapp-API/gradio.md
      - Docker: Webapp-API/docker.md
      - Developing/Contributing: Webapp-API/developing-contributing.md
